### ISSUE TITLE
after publication: Promote Your NEON Publication 

### ISSUE THREAD

**Issue by teixeirak** [EcoClimLab/vertical-thermal-review#116]
https://www.neonscience.org/promote-your-neon-publication

**Comment by teixeirak** [comment]
@NidhiVinod , now would be a good time to do this. I could fill it out if you'd like, but wanted to give you the chance to put it in your own words &  decide if you're interested in the opportunities.

**Comment by NidhiVinod** [comment]
@teixeirak, thank you for mentioning this, yes, I can fill it out!

**Comment by NidhiVinod** [comment]
@teixeirak, I am working on another NEON project where I am trying to calculate ecosystem parameters such as canopy conductance, water use efficiency, respiration etc.. for all the sites we sampled at. For the calculation, I need sensor heights for all NEON sites and was trying find it on the NEON website, but somehow I couldn't find it but then I remembered that we had requested for sensor heights at one point for the analysis Ian worked on, right? Do we still have the excel sheet?

**Comment by teixeirak** [comment]
> @teixeirak, I am working on another NEON project where I am trying to calculate ecosystem parameters such as canopy conductance, water use efficiency, respiration etc.. for all the sites we sampled at. For the calculation, I need sensor heights for all NEON sites and was trying find it on the NEON website, but somehow I couldn't find it but then I remembered that we had requested for sensor heights at one point for the analysis Ian worked on, right? Do we still have the excel sheet?

I believe this is the file you need: https://github.com/EcoClimLab/vertical-thermal-review/blob/master/NEON_height_profiles/data/site_data/TIS%20site%20metadata_20190403_forNOAA.xlsx.
