### ISSUE TITLE
make editable versions of Figures 2-4

### ISSUE THREAD

**Issue by teixeirak** [EcoClimLab/vertical-thermal-review#127]
@NidhiVinod , @mcgregorian1 , @ValentineHerr , The journal requested editable versions of Figs. 2-4 (NEON height profiles, tealeaves figure, and tree-rings figure). We've been through this with a couple Nature papers, and Valentine knows what to do. 

Valentine, could you please make an editable version of the tree-rings figure that you previously produced, and also copy the bit of R code here so that Nidhi and Ian know how to edit the figures they produced?

**Comment by ValentineHerr** [comment]
Looking into this now:

This is what needs to happen:

> In the code, you need to remove your statements before you plot the figure so the figure appears in your plotting device and replace dev.off() by
dev.copy2pdf(file="Figurename.pdf", useDingbats=FALSE, family="serif", width = 7.2, height = 8)

**Comment by ValentineHerr** [comment]
I pushed an editable pdf of the tree ring figure.

**Comment by teixeirak** [comment]
Thanks so much!

**Comment by NidhiVinod** [comment]
> Looking into this now:
> 
> This is what needs to happen:
> 
> > In the code, you need to remove your statements before you plot the figure so the figure appears in your plotting device and replace dev.off() by
> > dev.copy2pdf(file="Figurename.pdf", useDingbats=FALSE, family="serif", width = 7.2, height = 8)

@ValentineHerr, thank you so much for sharing the code!  I'm confused, do I enter dev.copy2pdf(file="Figurename.pdf", useDingbats=FALSE, family="serif", width = 7.2, height = 8) before the code? and then have the code underneath it?

**Comment by ValentineHerr** [comment]
no after, and make sure to update the file name but leave it as a pdf (and you may need to adjust the width and height

**Comment by teixeirak** [comment]
@mcgregorian1 just told me he's not feeling well and may not be able to get to this for awhile. Nidhi, perhaps you can make this tweak in his code and run it to produce the new figure?

**Comment by NidhiVinod** [comment]
@teixeirak, shoot, I'm getting an error with the code, but not sure where the error is from
<img width="891" alt="Screen Shot 2022-09-30 at 9 21 43 AM" src="https://user-images.githubusercontent.com/62031681/193314237-fb6c3c27-b5df-4d33-af1f-abefb8e12174.png">

**Comment by NidhiVinod** [comment]
> dev.copy2pdf(file="Figurename.pdf", useDingbats=FALSE, family="serif", width = 7.2, height = 8)

I fixed this error, but now I'm getting this:
<img width="868" alt="Screen Shot 2022-09-30 at 9 43 13 AM" src="https://user-images.githubusercontent.com/62031681/193317907-e6629245-99c0-4e3a-931f-7af9b19666f4.png">

@ValentineHerr, would you know why this would be?

**Comment by ValentineHerr** [comment]
Hi @NidhiVinod, are you running this line of code after the plot shows up in RStudio?

To make sure all is set, run `dev.off()` a few times in a row, until it throws you an error (this should close all the open plotting devices you may have), then run the code necessary to plot the figure, it should show up in R studio (so make sure there is no line of code that is,  e.g. `pdf()` or `png()` or `jpeg()` before your plot code).
Once you can see your figure within RStudio, run the `dev.copy2pdf(...)`.

If you still have an issue, try restarting R and try again.

If all fails, indicate the script and line of code you are working on and I'll try it myself.

**Comment by NidhiVinod** [comment]
@ValentineHerr, thank you so much! That worked!

**Comment by NidhiVinod** [comment]
@teixeirak, I was able to make Figure 2 and 3 editable through R, but the only thing is for Figure 3, I had made a few manual edits to make the table symbols subscripts for Gs and Tair etc... Do you know if the illustrator can do that?

**Comment by teixeirak** [comment]
I'd assume so. I'd sent it to them with a note. 

You got the version of Fig. 4 that Valentine made, correct?

**Comment by ValentineHerr** [comment]
You could try to do the same for that figure and edit it in PDF to make the subscripts.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by NidhiVinod** [comment]
> I'd assume so. I'd sent it to them with a note.
> 
> You got the version of Fig. 4 that Valentine made, correct?

Great! Yes, is it the one in Figures folder Valentine?

**Comment by teixeirak** [comment]
I'd recommend you just send what you have to the journal with an explanation of what needs to happen.

**Comment by ValentineHerr** [comment]
> > I'd assume so. I'd sent it to them with a note.
> > You got the version of Fig. 4 that Valentine made, correct?
> 
> Great! Yes, is it the one in Figures folder Valentine?

yes
